/**
 * Replace the generated splash bitmaps with a drawable that costs almost
 * nothing.
 *
 * `capacitor-assets` emits 26 full-screen PNGs — every density, portrait and
 * landscape, light and dark — which came to 3.8 MB, nearly half the APK. The
 * splash is a solid brand ground with the emblem centred on it, so a
 * layer-list plus one bitmap per density says the same thing in a fraction of
 * the space, and it is correct at every screen size and orientation instead of
 * only the ones that were pre-rendered.
 *
 * Run automatically by `npm run android:icons`, so regenerating the launcher
 * icons cannot leave a splash.png behind to collide with splash.xml.
 */

import { readdir, rm, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const RES = 'android/app/src/main/res';
const SOURCE = 'public/assets/haseeb-icon.png';
const INK = '#0F172A';

/** Emblem side in density-independent pixels. */
const EMBLEM_DP = 180;
const DENSITIES = { mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3 };

async function removeGeneratedBitmaps() {
  const dirs = await readdir(RES, { withFileTypes: true });
  let removed = 0;
  for (const dir of dirs) {
    if (!dir.isDirectory() || !dir.name.startsWith('drawable')) continue;
    const file = path.join(RES, dir.name, 'splash.png');
    if (existsSync(file)) {
      await rm(file);
      removed += 1;
    }
    // Density folders that existed only to hold a splash are now empty.
    const rest = await readdir(path.join(RES, dir.name));
    if (rest.length === 0) await rm(path.join(RES, dir.name), { recursive: true });
  }
  return removed;
}

async function writeEmblems() {
  for (const [density, scale] of Object.entries(DENSITIES)) {
    const dir = path.join(RES, `drawable-${density}`);
    await mkdir(dir, { recursive: true });
    const size = Math.round(EMBLEM_DP * scale);
    await sharp(SOURCE)
      .resize(size, size, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
      .png({ compressionLevel: 9 })
      .toFile(path.join(dir, 'splash_emblem.png'));
  }
}

async function writeLayerList() {
  await writeFile(
    path.join(RES, 'drawable', 'splash.xml'),
    `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/android-splash.mjs — do not edit by hand. -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/splashBackground" />
    <item>
        <bitmap
            android:src="@drawable/splash_emblem"
            android:gravity="center" />
    </item>
</layer-list>
`,
  );

  await writeFile(
    path.join(RES, 'values', 'splash.xml'),
    `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/android-splash.mjs — do not edit by hand. -->
<resources>
    <color name="splashBackground">${INK}</color>
</resources>
`,
  );
}

const removed = await removeGeneratedBitmaps();
await writeEmblems();
await writeLayerList();
console.log(`splash: replaced ${removed} bitmaps with a layer-list + ${Object.keys(DENSITIES).length} emblems`);
